# Assignment: Data Wrangling
## `! git clone https://github.com/DS3001/wrangling`
## Do Q2, and one of Q1 or Q3.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [4]:
! git clone https://github.com/will-mitchell22/wrangling

Cloning into 'wrangling'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 92 (delta 42), reused 18 (delta 18), pack-reused 40 (from 1)
Receiving objects: 100% (92/92), 18.08 MiB | 8.12 MiB/s, done.
Resolving deltas: 100% (43/43), done.

**Q1.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?
  2. Read the introduction. What is the "tidy data standard" intended to accomplish?
  3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, it’s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."
  4. Read Section 2.2. How does Wickham define values, variables, and observations?
  5. How is "Tidy Data" defined in section 2.3?
  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?
  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?
  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?

1. This paper is about the process of tidying data and making it more clean and efficient to manipulate and visualize.  The paper describes how vast quantities of effort are put into cleaning data, but there has been little work done to make this process more efficient.  The paper describes tools and effective ways to make data sets more tidy and easier to work with.

2. The "tidy data standard" is intended to create a much easier way to clean data, without having to "reinvent the wheel every time".  The "tidy data standard" allows for understanding and exploration of the data, and creating a simple and cohesive process that uses tools to efficiently clean the data.  The "tidy data standard" can be applied to varying data sets of different "messiness" levels, and can have a similar process using similar tools to make the cleaning job much easier.

3. The sentence "Like families, tidy datasets are all alike but every messy dataset is messy in its own way", means that when datasets are tidy, they will all follow a similar structure/plan to one another, and skills used to analyze one will be easily transferrable to the next.  Messy datasets on the other hand, are all different in their own way because there is no set way that a data set can be messy, leading to problem solving from Data Scientists to clean the data.  The sentence "For a given dataset, it's usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define values, variables, and observations", means that when you have variables and observations, it is easy to tell which are which, but in certain instances, defining the variables and observations themselves can be confusing.  The reading gives an example of hight and width both being values of a dimension variable, showing how these variables can now be linked together under one.

4. Wickham defines values as as either numbers or strings, organized in two ways where they beling to a variable and an observation.  Variables contain all values that measure the same underlying attribute across units.  Observations contain all the values measured on the same unit across attributes.

5. "Tidy Data" is defined in section 2.3 as a standard way of mapping the meaning of a dataset to its structure.  Within a tidy dataset, there each variable forms a column, each observation forms a row, and each type of observational unit forms a table.  Messy data is also described as any sort of deviation from this alignment.

6. The five most common problems with messy datasets are, that column headers are values, not variable names, multiple variables are stored in one column, variables are stored in both rows and columns, multiple types of observational units are stored in the same table, and that a single observational unit is stored in multiple tables.  The data in table 4 is messy data because this table is designed for presentation, but the column headers are values, not variable names and variables form both the rows and the columns.  Melting a dataset means to essentially stack it by turning columns into rows.

7. Table 11 is messy because it has variables stored in both rows and columns.  It has variables in individual colums, spread across columns, and across rows.  Table 12 is tidy and molten by having an almost tidy dataset, but the element column contains the names of variables, and then the tidy data having each row representing measurements for a single day.

8. The "chicken-and-egg" problem with focusing on tidy data is that if tidy data is only as useful as the tools that work with it, then tidy tools will be inextricably linked to tidy data.  Wickham hopes that in the future others will build on the tidy data framework to develop better data storage strategies and better tools. Wickham hopes that in the future to use methodologies from varying fields to improve understanding in the cognitive side of data analysis and improve design abilities.  Wickham also stated that we could consider tidy tools that can automatically choose between array-tidy and dataframe-tidy formats to optimize memory usage and performance.

**Q2.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the `./data/sharks.csv` data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.
3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df = pd.read_csv('/content/wrangling/assignment/data/airbnb_hw.csv')
print(df.shape, '\n')
df.head()

(30478, 13)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [7]:
price = df['Price']
price.unique()

array(['145', '37', '28', '199', '549', '149', '250', '90', '270', '290',
       '170', '59', '49', '68', '285', '75', '100', '150', '700', '125',
       '175', '40', '89', '95', '99', '499', '120', '79', '110', '180',
       '143', '230', '350', '135', '85', '60', '70', '55', '44', '200',
       '165', '115', '74', '84', '129', '50', '185', '80', '190', '140',
       '45', '65', '225', '600', '109', '1,990', '73', '240', '72', '105',
       '155', '160', '42', '132', '117', '295', '280', '159', '107', '69',
       '239', '220', '399', '130', '375', '585', '275', '139', '260',
       '35', '133', '300', '289', '179', '98', '195', '29', '27', '39',
       '249', '192', '142', '169', '1,000', '131', '138', '113', '122',
       '329', '101', '475', '238', '272', '308', '126', '235', '315',
       '248', '128', '56', '207', '450', '215', '210', '385', '445',
       '136', '247', '118', '77', '76', '92', '198', '205', '299', '222',
       '245', '104', '153', '349', '114', '320', '292', '226', '420',
       '500', '325', '307', '78', '265', '108', '123', '189', '32', '58',
       '86', '219', '800', '335', '63', '229', '425', '67', '87', '1,200',
       '158', '650', '234', '310', '695', '400', '166', '119', '62',
       '168', '340', '479', '43', '395', '144', '52', '47', '529', '187',
       '209', '233', '82', '269', '163', '172', '305', '156', '550',
       '435', '137', '124', '48', '279', '330', '5,000', '134', '378',
       '97', '277', '64', '193', '147', '186', '264', '30', '3,000',
       '112', '94', '379', '57', '415', '236', '410', '214', '88', '66',
       '71', '171', '157', '545', '1,500', '83', '96', '1,800', '81',
       '188', '380', '255', '505', '54', '33', '174', '93', '740', '640',
       '1,300', '440', '599', '357', '1,239', '495', '127', '5,999',
       '178', '348', '152', '242', '183', '253', '750', '259', '365',
       '273', '197', '397', '103', '389', '355', '559', '38', '203',
       '999', '141', '162', '333', '698', '46', '360', '895', '10', '41',
       '206', '281', '449', '388', '212', '102', '201', '2,750', '4,750',
       '432', '675', '167', '390', '298', '339', '194', '302', '211',
       '595', '191', '53', '361', '480', '8,000', '4,500', '459', '997',
       '345', '216', '218', '111', '735', '276', '91', '490', '850',
       '398', '36', '775', '267', '625', '336', '2,500', '176', '725',
       '3,750', '469', '106', '460', '287', '575', '227', '263', '25',
       '228', '208', '177', '880', '148', '116', '685', '470', '217',
       '164', '61', '645', '699', '405', '252', '319', '268', '419',
       '343', '525', '311', '840', '154', '294', '950', '409', '184',
       '257', '204', '241', '2,000', '412', '121', '288', '196', '900',
       '647', '524', '1,750', '309', '510', '1,495', '1,700', '799',
       '383', '372', '492', '327', '1,999', '656', '224', '173', '875',
       '1,170', '795', '690', '146', '465', '1,100', '151', '274', '429',
       '825', '282', '256', '1,111', '620', '271', '161', '51', '855',
       '579', '1,174', '430', '20', '899', '649', '485', '181', '455',
       '4,000', '243', '342', '590', '560', '374', '437', '232', '359',
       '985', '31', '244', '254', '723', '237', '428', '370', '34',
       '1,400', '580', '2,520', '221', '749', '1,600', '2,695', '306',
       '202', '680', '570', '520', '223', '2,295', '213', '1,065', '346',
       '24', '286', '296', '266', '26', '995', '1,368', '393', '182',
       '635', '258', '780', '589', '347', '1,250', '1,350', '446',
       '3,200', '1,050', '1,650', '1,550', '975', '323', '6,500', '2,499',
       '1,850', '2,250', '715', '461', '540', '356', '439', '384', '569',
       '1,900', '22', '785', '626', '830', '318', '444', '321', '401',
       '1,499', '888', '369', '770', '386', '366', '344', '630', '313',
       '597', '262', '509', '10,000', '278', '312', '789', '1,195', '422',
       '21', '765', '3,500', '945', '326', '3,100', '2,486', '3,390',
       '1,356', '2,599', '472', '454', '328', '396', '291'], dtype=object)

In [8]:
price = df['Price']
price = price.str.replace(',','.') # This will replace the commas with periods.
print(price.unique() , '\n')
price = pd.to_numeric(price,errors='coerce') # This will change price to a float/numeric type of variable
print(price.unique(), '\n')
print('Total missing: ', sum(price.isnull())) # This will count the number of missing values

['145' '37' '28' '199' '549' '149' '250' '90' '270' '290' '170' '59' '49'
 '68' '285' '75' '100' '150' '700' '125' '175' '40' '89' '95' '99' '499'
 '120' '79' '110' '180' '143' '230' '350' '135' '85' '60' '70' '55' '44'
 '200' '165' '115' '74' '84' '129' '50' '185' '80' '190' '140' '45' '65'
 '225' '600' '109' '1.990' '73' '240' '72' '105' '155' '160' '42' '132'
 '117' '295' '280' '159' '107' '69' '239' '220' '399' '130' '375' '585'
 '275' '139' '260' '35' '133' '300' '289' '179' '98' '195' '29' '27' '39'
 '249' '192' '142' '169' '1.000' '131' '138' '113' '122' '329' '101' '475'
 '238' '272' '308' '126' '235' '315' '248' '128' '56' '207' '450' '215'
 '210' '385' '445' '136' '247' '118' '77' '76' '92' '198' '205' '299'
 '222' '245' '104' '153' '349' '114' '320' '292' '226' '420' '500' '325'
 '307' '78' '265' '108' '123' '189' '32' '58' '86' '219' '800' '335' '63'
 '229' '425' '67' '87' '1.200' '158' '650' '234' '310' '695' '400' '166'
 '119' '62' '168' '340' '479' '43' '395' '144' '52' '47' '529' '187' '209'
 '233' '82' '269' '163' '172' '305' '156' '550' '435' '137' '124' '48'
 '279' '330' '5.000' '134' '378' '97' '277' '64' '193' '147' '186' '264'
 '30' '3.000' '112' '94' '379' '57' '415' '236' '410' '214' '88' '66' '71'
 '171' '157' '545' '1.500' '83' '96' '1.800' '81' '188' '380' '255' '505'
 '54' '33' '174' '93' '740' '640' '1.300' '440' '599' '357' '1.239' '495'
 '127' '5.999' '178' '348' '152' '242' '183' '253' '750' '259' '365' '273'
 '197' '397' '103' '389' '355' '559' '38' '203' '999' '141' '162' '333'
 '698' '46' '360' '895' '10' '41' '206' '281' '449' '388' '212' '102'
 '201' '2.750' '4.750' '432' '675' '167' '390' '298' '339' '194' '302'
 '211' '595' '191' '53' '361' '480' '8.000' '4.500' '459' '997' '345'
 '216' '218' '111' '735' '276' '91' '490' '850' '398' '36' '775' '267'
 '625' '336' '2.500' '176' '725' '3.750' '469' '106' '460' '287' '575'
 '227' '263' '25' '228' '208' '177' '880' '148' '116' '685' '470' '217'
 '164' '61' '645' '699' '405' '252' '319' '268' '419' '343' '525' '311'
 '840' '154' '294' '950' '409' '184' '257' '204' '241' '2.000' '412' '121'
 '288' '196' '900' '647' '524' '1.750' '309' '510' '1.495' '1.700' '799'
 '383' '372' '492' '327' '1.999' '656' '224' '173' '875' '1.170' '795'
 '690' '146' '465' '1.100' '151' '274' '429' '825' '282' '256' '1.111'
 '620' '271' '161' '51' '855' '579' '1.174' '430' '20' '899' '649' '485'
 '181' '455' '4.000' '243' '342' '590' '560' '374' '437' '232' '359' '985'
 '31' '244' '254' '723' '237' '428' '370' '34' '1.400' '580' '2.520' '221'
 '749' '1.600' '2.695' '306' '202' '680' '570' '520' '223' '2.295' '213'
 '1.065' '346' '24' '286' '296' '266' '26' '995' '1.368' '393' '182' '635'
 '258' '780' '589' '347' '1.250' '1.350' '446' '3.200' '1.050' '1.650'
 '1.550' '975' '323' '6.500' '2.499' '1.850' '2.250' '715' '461' '540'
 '356' '439' '384' '569' '1.900' '22' '785' '626' '830' '318' '444' '321'
 '401' '1.499' '888' '369' '770' '386' '366' '344' '630' '313' '597' '262'
 '509' '10.000' '278' '312' '789' '1.195' '422' '21' '765' '3.500' '945'
 '326' '3.100' '2.486' '3.390' '1.356' '2.599' '472' '454' '328' '396'
 '291']

[145.     37.     28.    199.    549.    149.    250.     90.    270.
 290.    170.     59.     49.     68.    285.     75.    100.    150.
 700.    125.    175.     40.     89.     95.     99.    499.    120.
  79.    110.    180.    143.    230.    350.    135.     85.     60.
  70.     55.     44.    200.    165.    115.     74.     84.    129.
  50.    185.     80.    190.    140.     45.     65.    225.    600.
 109.      1.99   73.    240.     72.    105.    155.    160.     42.
 132.    117.    295.    280.    159.    107.     69.    239.    220.
 399.    130.    375.    585.    275.    139.    260.     35.    133.
 300.    289.    179.     98.    195.     29.     27.     39.    249.
 192.    142.    169.      1.    131.    138.    113.    122.    329.
 101.    475.    238.    272.    308.    126.    235.    315.    248.
 128.     56.    207.    450.    215.    210.    385.    445.    136.
 247.    118.     77.     76.     92.    198.    205.    299.    222.
 245.    104.    153.    349.    114.    320.    292.    226.    420.
 500.    325.    307.     78.    265.    108.    123.    189.     32.
  58.     86.    219.    800.    335.     63.    229.    425.     67.
  87.      1.2   158.    650.    234.    310.    695.    400.    166.
 119.     62.    168.    340.    479.     43.    395.    144.     52.
  47.    529.    187.    209.    233.     82.    269.    163.    172.
 305.    156.    550.    435.    137.    124.     48.    279.    330.
   5.    134.    378.     97.    277.     64.    193.    147.    186.
 264.     30.      3.    112.     94.    379.     57.    415.    236.
 410.    214.     88.     66.     71.    171.    157.    545.      1.5
  83.     96.      1.8    81.    188.    380.    255.    505.     54.
  33.    174.     93.    740.    640.      1.3   440.    599.    357.
   1.239 495.    127.      5.999 178.    348.    152.    242.    183.
 253.    750.    259.    365.    273.    197.    397.    103.    389.
 355.    559.     38.    203.    999.    141.    162.    333.    698.
  46.    360.    895.     10.     41.    206.    281.    449.    388.
 212.    102.    201.      2.75    4.75  432.    675.    167.    390.
 298.    339.    194.    302.    211.    595.    191.     53.    361.
 480.      8.      4.5   459.    997.    345.    216.    218.    111.
 735.    276.     91.    490.    850.    398.     36.    775.    267.
 625.    336.      2.5   176.    725.      3.75  469.    106.    460.
 287.    575.    227.    263.     25.    228.    208.    177.    880.
 148.    116.    685.    470.    217.    164.     61.    645.    699.
 405.    252.    319.    268.    419.    343.    525.    311.    840.
 154.    294.    950.    409.    184.    257.    204.    241.      2.
 412.    121.    288.    196.    900.    647.    524.      1.75  309.
 510.      1.495   1.7   799.    383.    372.    492.    327.      1.999
 656.    224.    173.    875.      1.17  795.    690.    146.    465.
   1.1   151.    274.    429.    825.    282.    256.      1.111 620.
 271.    161.     51.    855.    579.      1.174 430.     20.    899.
 649.    485.    181.    455.      4.    243.    342.    590.    560.
 374.    437.    232.    359.    985.     31.    244.    254.    723.
 237.    428.    370.     34.      1.4   580.      2.52  221.    749.
   1.6     2.695 306.    202.    680.    570.    520.    223.      2.295
 213.      1.065 346.     24.    286.    296.    266.     26.    995.
   1.368 393.    182.    635.    258.    780.    589.    347.      1.25
   1.35  446.      3.2     1.05    1.65    1.55  975.    323.      6.5
   2.499   1.85    2.25  715.    461.    540.    356.    439.    384.
 569.      1.9    22.    785.    626.    830.    318.    444.    321.
 401.      1.499 888.    369.    770.    386.    366.    344.    630.
 313.    597.    262.    509.    278.    312.    789.      1.195 422.
  21.    765.      3.5   945.    326.      3.1     2.486   3.39    1.356
   2.599 472.    454.    328.    396.    291.   ]

Total missing:  0

In [8]:
df = pd.read_csv('/content/wrangling/assignment/data/sharks.csv', low_memory=False)
df.head()
df.columns.tolist() # These two functions will show the dataframe and convert them to columns

['index',
 'Case Number',
 'Date',
 'Year',
 'Type',
 'Country',
 'Area',
 'Location',
 'Activity',
 'Name',
 'Unnamed: 9',
 'Age',
 'Injury',
 'Fatal (Y/N)',
 'Time',
 'Species ',
 'Investigator or Source',
 'pdf',
 'href formula',
 'href',
 'Case Number.1',
 'Case Number.2',
 'original order',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 'Unnamed: 64',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'Unnamed: 68',
 'Unnamed: 69',
 'Unnamed: 70',
 'Unnamed: 71',
 'Unnamed: 72',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 'Unnamed: 78',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 'Unnamed: 84',
 'Unnamed: 85',
 'Unnamed: 86',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 'Unnamed: 92',
 'Unnamed: 93',
 'Unnamed: 94',
 'Unnamed: 95',
 'Unnamed: 96',
 'Unnamed: 97',
 'Unnamed: 98',
 'Unnamed: 99',
 'Unnamed: 100',
 'Unnamed: 101',
 'Unnamed: 102',
 'Unnamed: 103',
 'Unnamed: 104',
 'Unnamed: 105',
 'Unnamed: 106',
 'Unnamed: 107',
 'Unnamed: 108',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 'Unnamed: 112',
 'Unnamed: 113',
 'Unnamed: 114',
 'Unnamed: 115',
 'Unnamed: 116',
 'Unnamed: 117',
 'Unnamed: 118',
 'Unnamed: 119',
 'Unnamed: 120',
 'Unnamed: 121',
 'Unnamed: 122',
 'Unnamed: 123',
 'Unnamed: 124',
 'Unnamed: 125',
 'Unnamed: 126',
 'Unnamed: 127',
 'Unnamed: 128',
 'Unnamed: 129',
 'Unnamed: 130',
 'Unnamed: 131',
 'Unnamed: 132',
 'Unnamed: 133',
 'Unnamed: 134',
 'Unnamed: 135',
 'Unnamed: 136',
 'Unnamed: 137',
 'Unnamed: 138',
 'Unnamed: 139',
 'Unnamed: 140',
 'Unnamed: 141',
 'Unnamed: 142',
 'Unnamed: 143',
 'Unnamed: 144',
 'Unnamed: 145',
 'Unnamed: 146',
 'Unnamed: 147',
 'Unnamed: 148',
 'Unnamed: 149',
 'Unnamed: 150',
 'Unnamed: 151',
 'Unnamed: 152',
 'Unnamed: 153',
 'Unnamed: 154',
 'Unnamed: 155',
 'Unnamed: 156',
 'Unnamed: 157',
 'Unnamed: 158',
 'Unnamed: 159',
 'Unnamed: 160',
 'Unnamed: 161',
 'Unnamed: 162',
 'Unnamed: 163',
 'Unnamed: 164',
 'Unnamed: 165',
 'Unnamed: 166',
 'Unnamed: 167',
 'Unnamed: 168',
 'Unnamed: 169',
 'Unnamed: 170',
 'Unnamed: 171',
 'Unnamed: 172',
 'Unnamed: 173',
 'Unnamed: 174',
 'Unnamed: 175',
 'Unnamed: 176',
 'Unnamed: 177',
 'Unnamed: 178',
 'Unnamed: 179',
 'Unnamed: 180',
 'Unnamed: 181',
 'Unnamed: 182',
 'Unnamed: 183',
 'Unnamed: 184',
 'Unnamed: 185',
 'Unnamed: 186',
 'Unnamed: 187',
 'Unnamed: 188',
 'Unnamed: 189',
 'Unnamed: 190',
 'Unnamed: 191',
 'Unnamed: 192',
 'Unnamed: 193',
 'Unnamed: 194',
 'Unnamed: 195',
 'Unnamed: 196',
 'Unnamed: 197',
 'Unnamed: 198',
 'Unnamed: 199',
 'Unnamed: 200',
 'Unnamed: 201',
 'Unnamed: 202',
 'Unnamed: 203',
 'Unnamed: 204',
 'Unnamed: 205',
 'Unnamed: 206',
 'Unnamed: 207',
 'Unnamed: 208',
 'Unnamed: 209',
 'Unnamed: 210',
 'Unnamed: 211',
 'Unnamed: 212',
 'Unnamed: 213',
 'Unnamed: 214',
 'Unnamed: 215',
 'Unnamed: 216',
 'Unnamed: 217',
 'Unnamed: 218',
 'Unnamed: 219',
 'Unnamed: 220',
 'Unnamed: 221',
 'Unnamed: 222',
 'Unnamed: 223',
 'Unnamed: 224',
 'Unnamed: 225',
 'Unnamed: 226',
 'Unnamed: 227',
 'Unnamed: 228',
 'Unnamed: 229',
 'Unnamed: 230',
 'Unnamed: 231',
 'Unnamed: 232',
 'Unnamed: 233',
 'Unnamed: 234',
 'Unnamed: 235',
 'Unnamed: 236',
 'Unnamed: 237',
 'Unnamed: 238',
 'Unnamed: 239',
 'Unnamed: 240',
 'Unnamed: 241',
 'Unnamed: 242',
 'Unnamed: 243',
 'Unnamed: 244',
 'Unnamed: 245',
 'Unnamed: 246',
 'Unnamed: 247',
 'Unnamed: 248',
 'Unnamed: 249',
 'Unnamed: 250',
 'Unnamed: 251',
 'Unnamed: 252',
 'Unnamed: 253',
 'Unnamed: 254',
 'Unnamed: 255']

In [9]:
df['Type'].value_counts() # This counts values

Type
Unprovoked             4716
Provoked                593
Invalid                 552
Sea Disaster            239
Watercraft              142
Boat                    109
Boating                  92
Questionable             10
Unconfirmed               1
Unverified                1
Under investigation       1
Boatomg                   1
Name: count, dtype: int64

In [10]:
type = df['Type'] #This allows for the Type variable to have values
type = type.replace(['Sea Disaster', 'Boat', 'Boating', 'Boatomg'], 'Watercraft') #This is all of the values related to watersports removed being added to Watercraft
type.value_counts()
type = type.replace(['Questionable', 'Unconfirmed', 'Unverified', 'Under investigation'],np.nan) # This disregards these values
type.value_counts()
df['Type'] = type # Allows for a clean version
del type # Then destroys the temporary 'Type'
df['Type'].value_counts()

Type
Unprovoked    4716
Provoked       593
Watercraft     583
Invalid        552
Name: count, dtype: int64

In [12]:
df = pd.read_parquet('/content/wrangling/data/justice_data.parquet')
df.head()
df.columns.tolist() # These will display the dataframe in a cleaner format

['InternalStudyID',
 'REQ_REC#',
 'Defendant_Sex',
 'Defendant_Race',
 'Defendant_BirthYear',
 'Defendant_Age',
 'Defendant_AgeGroup',
 'Defendant_AgeatCurrentArrest',
 'Defendant_AttorneyTypeAtCaseClosure',
 'Defendant_IndigencyStatus',
 'Defendant_RecordedZipCode_eMag',
 'Defendant_VirginiaResidencyStatus',
 'WhetherDefendantWasReleasedPretrial',
 'PretrialReleaseDate',
 'DaysBetweenContactEventAndPretrialRelease',
 'PretrialReleaseType1',
 'PretrialReleaseType2',
 'BondTypeAtInitialContact',
 'BondAmountAtInitialContact',
 'BondTypeAtRelease_v1',
 'BondTypeatRelease_v2',
 'BondAmountAtRelease',
 'WhetherDefendantReceivedPretrialServicesAgencySuperv_PTCC',
 'DaysBetweenReleaseandActivePretrialServicesAgencySupervDate',
 'DaysBetweenPretrialServicesAgencySupervReferralDateandSupervDate',
 'Indicator_PresumptiveDenialOfBail_19.2_120',
 'Indicator_ConditionsToBeReleasedSecuredBond_19.2_123',
 'IfReleasedonSecuredBond_TypeofSurety',
 'Indicator_BailTermSetByCourt_eMag',
 'AdditionalJailTimeServedAfterInitialPretrialRelease',
 'Oct2017_ContactEventDate',
 'ContactEventType',
 'ContactEvent_OverallTypeofOffense_v1',
 'ContactEvent_OverallTypeofOffense_v2',
 'ContactEvent_WhetherOffensePunishablebyIncaration',
 'ContactEvent_CourtType',
 'NumberOffenseTypesinContactEvent',
 'VCC_MostSerChargeinContactEvent_regardlessofFinalDisp',
 'VCCPrefix_MostSerChargeinCharge_regardlessofFinalDisp',
 'VCCClassification_MostSerChargeinCharge_regardlessofFinalDisp',
 'VCC_SecondOffenseType_ifany',
 'VCC_ThirdOffenseType_ifany',
 'VCC_FourthOffenseType_ifany',
 'VCC_FifthOffenseType_ifany',
 'VCC_SixthOffenseType_ifany',
 'VCC_SeventhOffenseType_ifany',
 'VCC_EightOffenseType_ifany',
 'VCC_NinthOffenseType_ifany',
 'VCC_TenthOffenseType_ifany',
 'CodeSection_MostSerChargeinContactEvent_regardlessofFinalDisp',
 'CodeSection_SecondOffenseType_ifany',
 'CodeSection_ThirdOffenseType_ifany',
 'CodeSection_FourthOffenseType_ifany',
 'CodeSection_FifthOffenseType_ifany',
 'CodeSection_SixthOffenseType_ifany',
 'CodeSection_SeventhOffenseType_ifany',
 'CodeSection_EightOffenseType_ifany',
 'CodeSection_NinthOffenseType_ifany',
 'CodeSection_TenthOffenseType_ifany',
 'CaseType_MostSerChargeinContactEvent_regardlessofFinalDisp',
 'CaseType_SecondOffenseType_ifany',
 'CaseType_ThirdOffenseType_ifany',
 'CaseType_FourthOffenseType_ifany',
 'CaseType_FifthOffenseType_ifany',
 'CaseType_SixthOffenseType_ifany',
 'CaseType_SeventhOffenseType_ifany',
 'CaseType_EightOffenseType_ifany',
 'CaseType_NinthOffenseType_ifany',
 'CaseType_TenthOffenseType_ifany',
 'OffenseCounts_MostSerChargeinContactEvent_regardlessofFinalDisp',
 'OffenseCounts_SecondOffenseType_ifany',
 'OffenseCounts_ThirdOffenseType_ifany',
 'OffenseCounts_FourthOffenseType_ifany',
 'OffenseCounts_FifthOffenseType_ifany',
 'OffenseCounts_SixthOffenseType_ifany',
 'OffenseCounts_SeventhOffenseType_ifany',
 'OffenseCounts_EightOffenseType_ifany',
 'OffenseCounts_NinthOffenseType_ifany',
 'OffenseCounts_TenthOffenseType_ifany',
 'CurrentCharge_FelDrugLarFraud',
 'CurrentCharge_FelDrug',
 'CurrentCharge_MisdDrug',
 'CurrentCharge_VPRAIViolent',
 'CurrentCharge_PSAViolent',
 'CurrentCharge_PSAViolentAgeLT21Yrs',
 'VCC_MostSerCharge_resultinginsentencing',
 'VCCPrefix_MostSerCharge_resultinginsentencing',
 'VCCClassification_MostSerCharge_resultinginsentencing',
 'CodeSection_MostSerCharge',
 'CaseType_MostSerCharge',
 'MAG_BailType',
 'MAG_BailAmount',
 'MAG_Cond_AvoidAllContact',
 'MAG_Cond_MaintainCommEduc',
 'MAG_Cond_ComplywithCurfew',
 'MAG_Cond_HomeElecIncar',
 'MAG_Cond_AccompOfficer',
 'MAG_Cond_RefrainAlcohol',
 'MAG_Cond_RefrainContolSub',
 'MAG_Cond_RefrainWeapon',
 'MAG_Cond_MaintSeekEmp',
 'MAG_Cond_SubmitDrugAlcoholScr',
 'MAG_Cond_SubmitDrugAlcoholTest',
 'MAG_Cond_MonitorGPS',
 'PTCC_RecFound',
 'PTCC_AddlRecFound',
 'PTCC_ServerName',
 'PTCC_RefType',
 'PTCC_PretrialSupPlacement',
 'PTCC_TypePlacement',
 'PTCC_DateFirstActive',
 'PTCC_JudicialOfficerType',
 'PTCC_CourtLocality',
 'PTCC_CourtType',
 'PTCC_ReferralDate',
 'PTCC_PlacementDate',
 'PTCC_PlacementType',
 'PTCC_TransferredIn',
 'PTCC_CourtReinstatement',
 'PTCC_BondType',
 'PTCC_JudicialAction',
 'PTCC_PlacementRiskLevel',
 'PTCC_OrigBondType',
 'PTCC_CurrBondType',
 'PTCC_OrigChargeBondAmt',
 'PTCC_ChargeBondAmt',
 'PTCC_Screening_OrigBondType',
 'PTCC_Screening_CurrBondType',
 'PTCC_Screening_OrigChargeBondAmt',
 'PTCC_Screening_ChargeBondAmt',
 'PTCC_PlaceRiskAsmtMostSeriousChargeCat',
 'PTCC_PlacementStatusatDataExtract',
 'PTCC_PendingClosedInd',
 'PTCC_SupervisionDys',
 'PTCC_CondOrdered',
 'PTCC_Cond_ReporttoPT',
 'PTCC_Cond_ExcessAlcDrugs',
 'PTCC_Cond_SubmitTesting',
 'PTCC_Cond_RefrainFirearm',
 'PTCC_Cond_NoContactVic',
 'PTCC_Cond_MaintSeekEmp',
 'PTCC_Cond_MaintSeekEduc',
 'PTCC_Cond_ComplywithCurfew',
 'PTCC_Cond_ElecMonitoring',
 'PTCC_Cond_RestrictTravel',
 'PTCC_ResQ_PriorMisd',
 'PTCC_ResQ_PriorFel',
 'PTCC_ResQ_PriorNumViolConv',
 'PTCC_ResQ_PriorFTAs',
 'PTCC_ResQ_PriorFTAOverTwoYrs',
 'PTCC_ResQ_PriorSenttoIncar',
 'PTCC_VPRAI_ActiveSupervision',
 'PTCC_VPRAI_FelDrugTheftFraud',
 'PTCC_VPRAI_PendingCharge',
 'PTCC_VPRAI_CrimHistory',
 'PTCC_VPRAI_TwoFTAs',
 'PTCC_VPRAI_TwoViolConv',
 'PTCC_VPRAI_EmpStatus',
 'PTCC_VPRAI_LastGradeComp',
 'PTCC_PraxisApplies',
 'PTCC_PraxisSupLevel',
 'PTCC_AssignedSupLevel',
 'PTCC_SupViolation',
 'PendingChargeatTimeofContactEvent_VPRAIdefinition',
 'PendingChargeatTimeofContactEvent_VPRAI_FTAdefinition',
 'PendingChargeatTimeofContactEvent_VPRAI_NotFTAdefinition',
 'PendingChargeatTimeofContactEvent_PSAdefinition',
 'AgeatFirstAdultArrest',
 'PriorArrests',
 'PriorArrests_Fel',
 'PriorArrests_Misd',
 'PriorArrests_Misd_InclNonJailable',
 'PriorArrests_DomAsl',
 'PriorArrests_FelProbSSVViol',
 'PriorArrests_MisdProbSSVViol',
 'PriorConvictions_Any',
 'PriorConvs_AdultOnly',
 'PriorConvs_Past2Yrs',
 'PriorConvs_Past5Yrs',
 'PriorConvs_Fel',
 'PriorConvs_Fel_Past2Yrs',
 'PriorConvs_Fel_Past5Yrs',
 'PriorConvs_Misd',
 'PriorConvs_Misd_Past2Yrs',
 'PriorConvs_Misd_Past5Yrs',
 'PriorConvs_Misd_InclNonJailable',
 'PriorConvs_Misd_CrimTraf',
 'PriorConvs_DomAsl',
 'PriorConvs_FelProbSSVViol',
 'PriorConvs_MisdProbSSVViol',
 'PriorDrugConvs_NonMJDist_Fel',
 'PriorDrugConvs_NonMJDist_Misd',
 'PriorDrugConvs_NonMJPoss_Fel',
 'PriorDrugConvs_NonMJPoss_Misd',
 'PriorDrugConvs_MJDist_Fel',
 'PriorDrugConvs_MJDist_Misd',
 'PriorDrugConvs_MJPoss',
 'PriorDrugConvs_UnkDrugDist_Fel',
 'PriorDrugConvs_UnkDrugPoss_Fel',
 'PriorDrugConvs_TypeNotClear_Fel',
 'PriorDrugConvs_TypeNotClear_Misd',
 'PriorAlcConvs',
 'PriorFTACharges',
 'PriorFTACharges_Past2Yrs',
 'PriorFTACharges_MoreThan2Yrs',
 'PriorFTAConvs',
 'PriorFTAConvs_Past2Yrs',
 'PriorFTAConvs_MoreThan2Yrs',
 'PriorVPRAIViolArrests',
 'PriorVPRAIViolArrests_Fel',
 'PriorVPRAIViolArrests_Misd',
 'PriorVPRAIViolArrests_DomAsl',
 'PriorVPRAIViolArrests_Past2Yrs',
 'PriorVPRAIViolArrests_Past5Yrs',
 'PriorVPRAIViolConvs',
 'PriorVPRAIViolConvs_Fel',
 'PriorVPRAIViolConvs_Misd',
 'PriorVPRAIViolConvs_DomAsl',
 'PriorVPRAIViolConvs_Past2Yrs',
 'PriorVPRAIViolConvs_Past5Yrs',
 'PriorPSAViolArrests',
 'PriorPSAViolArrests_Fel',
 'PriorPSAViolArrests_Misd',
 'PriorPSAViolArrests_DomAsl',
 'PriorPSAViolArrests_Past2Yrs',
 'PriorPSAViolArrests_Past5Yrs',
 'PriorPSAViolConvs',
 'PriorPSAViolConvs_Fel',
 'PriorPSAViolConvs_Misd',
 'PriorPSAViolConvs_DomAsl',
 'PriorPSAViolConvs_Past2Yrs',
 'PriorPSAViolConvs_Past5Yrs',
 'Prior805ViolArrests',
 'Prior805ViolArrests_Past2Yrs',
 'Prior805ViolArrests_Past5Yrs',
 'Prior805ViolConvs',
 'Prior805ViolConvs_Past2Yrs',
 'Prior805ViolConvs_Past5Yrs',
 'Prior297ViolArrests',
 'Prior297ViolArrests_Past2Yrs',
 'Prior297ViolArrests_Past5Yrs',
 'Prior297ViolConvs',
 'Prior297ViolConvs_Past2Yrs',
 'Prior297ViolConvs_Past5Yrs',
 'PriorConvs_FelPerson',
 'PriorConvs_FelProperty',
 'PriorConvs_FelDrug',
 'PriorConvs_FelOther',
 'PriorConvs_Fel_SameType',
 'PriorConvs_Misd_SameType',
 'PriorProbRevocations_Felony',
 'PriorProbRevocations_Misd',
 'PriorSentEvents_Fel',
 'PriorSentEvents_FelProbRevocations',
 'PriorSentEvents_MisdProbRevocations',
 'PriorSentEvents_FTA',
 'PriorIncarEvents_GE14Dys',
 'PriorIncarEvents_LT1Yr',
 'PriorIncarEvents_GE1Yr',
 'Defendant_WhetherOnStateProbationAtTimeofContactEvent',
 'Defendant_WhetherOnLocalProbationAtTimeofContactEvent',
 'VPRAI_Factor_ActiveCommSup',
 'VPRAI_Factor_CurrentFelDrugLarFraud',
 'VPRAI_Factor_PendingCharge',
 'VPRAI_Factor_AdultCriminalConv',
 'VPRAI_Factor_FTAs',
 'VPRAI_Factor_ViolentConvs',
 'VPRAI_Factor_Unemployed_Opt1',
 'VPRAI_Factor_Unemployed_Opt2',
 'VPRAI_Factor_PTUnemployment',
 'VPRAI_TotalPoints_Opt1',
 'VPRAI_RiskLevel_Opt1',
 'VPRAI_TotalPoints_Opt2',
 'VPRAI_RiskLevel_Opt2',
 'VPRAI_PTPlacementRiskLevel',
 'VPRAI_DifferenceinRiskLevel_Unemployed',
 'PSA_FTA_Factor_PendingCharge',
 'PSA_FTA_Factor_PriorConviction',
 'PSA_FTA_Factor_PriorFTAPast2Yrs',
 'PSA_FTA_Factor_PriorFTAMoreThan2Yrs',
 'PSA_FTA_TotalPoints',
 'PSA_FTA_RiskLevelScale',
 'PSA_NCA_Factor_AgeatArrest',
 'PSA_NCA_Factor_PendingCharge',
 'PSA_NCA_Factor_PriorMisdConv',
 'PSA_NCA_Factor_PriorFelConv',
 'PSA_NCA_Factor_PriorViolConv',
 'PSA_NCA_Factor_PriorFTAPast2Yrs',
 'PSA_NCA_Factor_PriorIncar',
 'PSA_NCA_TotalPoints',
 'PSA_NCA_RiskLevelScale',
 'PSA_NVCA_Factor_CurrentViolOff',
 'PSA_NVCA_Factor_CurrentViolOff20orYounger',
 'PSA_NVCA_Factor_PendingCharge',
 'PSA_NVCA_Factor_PriorConviction',
 'PSA_NVCA_Factor_PriorViolConv',
 'PSA_NVCA_TotalPoints',
 'PSA_NVCA_WhetherAssignedFlag',
 'Locality_FIPS',
 'Locality_Name',
 'Locality_Region',
 'Locality_JudicialCircuit',
 'Locality_JudicialDistrict',
 'Locality_MagisterialRegion',
 'Locality_PublicDefenderOfficePresence',
 'Locality_PretrialServicesAgencyPresence',
 'TotalPopulationEstimate_2017_Census',
 'Populationdensity_persquaremile_2010Census',
 'UnemploymentRate_October2017_BureauofLaborStatistics',
 'TotalSwornLawEnforcementOfficers_2017_VSPCrimeinVirginia',
 'GiniIndex',
 'WhiteAlone_PopulationEstimate_2017_Census',
 'WhiteAlonePercentage_PopulationEstimate_2017_Census',
 'AfricanAmericanAlone_PopulationEstimate_2017_Census',
 'AfricanAmericanAlonepercentage_PopulationEstimate_2017',
 'AsianAlone_PopulationEstimate_2017_Census',
 'AsianAlonepercentage_PopulationEstimate_2017_Census',
 'OtherRacesAlone_PopulationEstimate_2017_Census',
 'OtherRacesAlonepercentge_PopulationEstimate_2017_Census',
 'Twoormoreraces_PopulationEstimate_2017_Census',
 'Twoormoreracespercentage_PopulationEstimate_2017_Census',
 'HispanicOrigin_PopulationEstimate_2017_Census',
 'BothSexes_MedianAge_2017Census',
 'Male_MedianAge_2017Census',
 'Female_MedianAge_2017Census',
 'TotalMalePopulationEstimate_2017_Census',
 'Under5years_Malepopulation_2017Census',
 '@5to9years_Malepopulation_2017Census',
 '@10to14years_Malepopulation_2017Census',
 '@15to19years_Malepopulation_2017Census',
 '@20to24years_Malepopulation_2017Census',
 '@25to29years_Malepopulation_2017Census',
 '@30to34years_Malepopulation_2017Census',
 '@35to39years_Malepopulation_2017Census',
 '@40to44years_Malepopulation_2017Census',
 '@45to49years_Malepopulation_2017Census',
 '@50to54years_Malepopulation_2017Census',
 '@55to59years_Malepopulation_2017Census',
 '@60to64years_Malepopulation_2017Census',
 '@65to69years_Malepopulation_2017Census',
 '@70to74years_Malepopulation_2017Census',
 '@75to79_Malepopulation_2017Census',
 '@80to84years_Malepopulation_2017Census',
 '@85yearsandover_Malepopulation_2017Census',
 'Under18years_Malepopulation_2017Census',
 '@18to64years_Malepopulation_2017Census',
 '@65yearsandover_Malepopulation_2017Census',
 '@18yearsandover_Malepopulation_2017Census',
 'TotalFemalePopulationEstimate_2017Census',
 'Under5years_Femalepopulation_2017Census',
 '@5to9years_Femalepopulation_2017Census',
 '@10to14years_Femalepopulation_2017Census',
 '@15to19years_Femalepopulation_2017Census',
 '@20to24years_Femalepopulation_2017Census',
 '@25to29years_Femalepopulation_2017Census',
 '@30to34years_Femalepopulation_2017Census',
 '@35to39years_Femalepopulation_2017Census',
 '@40to44years_Femalepopulation_2017Census',
 '@45to49years_Femalepopulation_2017Census',
 '@50to54years_Femalepopulation_2017Census',
 '@55to59years_Femalepopulation_2017Census',
 '@60to64years_Femalepopulation_2017Census',
 '@65to69years_Femalepopulation_2017Census',
 '@70to74years_Femalepopulation_2017Census',
 '@75to79years_Femalepopulation_2017Census',
 '@80to84years_Femalepopulation_2017Census',
 '@85yearsandover_Femalepopulation_2017Census',
 'Under18years_Femalepopulation_2017Census',
 '@18to64years_Femalepopulation_2017Census',
 '@65yearsandover_Femalepopulation_2017Census',
 '@18yearsandover_Femalepopulation_2017Census',
 'TotalMALEANDFEMALEPopulation_2017Census',
 'Under5years_TotalPopulation_2017Census',
 '@5to9years_TotalPopulation_2017Census',
 '@10to14years_TotalPopulation_2017Census',
 '@15to19years_TotalPopulation_2017Census',
 '@20to24years_TotalPopulation_2017Census',
 '@25to29years_TotalPopulation_2017Census',
 '@30to34years_TotalPopulation_2017Census',
 '@35to39years_TotalPopulation_2017Census',
 '@40to44years_TotalPopulation_2017Census',
 '@45to49years_TotalPopulation_2017Census',
 '@50to54years_TotalPopulation_2017Census',
 '@55to59years_TotalPopulation_2017Census',
 '@60to64years_TotalPopulation_2017Census',
 '@65to69years_TotalPopulation_2017Census',
 '@70to74years_TotalPopulation_2017Census',
 '@75to79years_TotalPopulation_2017Census',
 '@80to84years_TotalPopulation_2017Census',
 '@85yearsandover_TotalPopulation_2017Census',
 'Under18years_TotalPopulation_2017Census',
 '@18to64years_TotalPopulation_2017Census',
 '@65yearsandover_TotalPopulation_2017Census',
 '@18yearsandover_TotalPopulation_2017Census',
 'Totalhouseholds_occupied_2017Census_A',
 'Percenthighschoolgraduateorhigher_2017Census',
 'Percentbachelorsdegreeorhigher_2017Census',
 'TotalCivilianNoninstitutionalizedPopulation_2017Census',
 'TotalCivilianNoninstitutionalizedPopulation_Withadisability',
 'PercentofTotalCivilianNoninstitutionalizedPopulation_Witha',
 'Estimate_RESIDENCE1YEARAGO_Population1yearandover_2017Ce',
 'EstimateRESIDENCE1YEARAGO_Population1yearandover_Sameh',
 'Percent_RESIDENCE1YEARAGO_Population1yearandover_Samehou',
 'Totalpopulation_Native_2017Census',
 'PercentTotalpopulation_Native_2017Census',
 'Totalpopulation_Foreignborn_2017Census',
 'PercentTotalpopulation_Foreignborn_2017Census',
 'Foreignbornpopulation_2017Census',
 'Foreignbornpopulation_NaturalizedU.S.citizen_2017Census',
 'PercentForeignbornpopulation_NaturalizedU.S.citizen_2017Cen',
 'Foreignbornpopulation_NotaU.S.citizen_2017Census',
 'PercentForeignbornpopulation_NotaU.S.citizen_2017Census',
 'Population5yearsandover_2017Census',
 'Population5yearsandover_Englishonly_2017Census',
 'PercentPopulation5yearsandover_Englishonly_2017Census',
 'Totalhouseholds_Withacomputer_2017Census',
 'PercentTotalhouseholds_Withacomputer_2017Census',
 'Totalhouseholds_WithabroadbandInternetsubscription_2017Cen',
 'PercentTotalhouseholds_WithabroadbandInternetsubscription',
 'Totalhousingunits_2017Census',
 'Totaloccupiedhousingunits_2017Census',
 'Occupiedhousingunits_2017Census',
 'TotalVacantHousingUnits_2017Census',
 'Percentvacanthousingunits_2017Census',
 'TotalHomeowndervacanyrate_2017Census',
 'Totalrentalvacanyrate_2017Census',
 'TotalOwneroccupiedhousingunits_2017Census',
 'Percentowneroccupiedhousingunits_2017Census',
 'Totalrenteroccupiedhousingunits_2017Census',
 'Percentrenteroccupiedhousingunits_2017Census',
 'Percentpopulationhighschoolgraduateorhigher_2017Census',
 'Percentpopulationbachelorsdegreeorhigher_2017Census',
 'Totalhouseholds_occupied_2017Census',
 'Totalhouseholds_Lessthan$10000inincome_2017Census',
 'PercentTotalhouseholds_Lessthan$10000inincome_2017Census',
 'Totalhouseholds$10000to$14999inincome_2017Census',
 'PercentTotalhouseholds$10000to$14999inincome_2017Censu',
 'Totalhouseholds$15000to$24999inincome_2017Census',
 'PercentTotalhouseholds$15000to$24999inincome_2017Censu',
 'Totalhouseholds$25000to$34999inincome_2017Census',
 'PercentTotalhouseholds$25000to$34999inincome_2017Censu',
 'Totalhouseholds$35000to$49999inincome_2017Census',
 'PercentTotalhouseholds$35000to$49999inincome_2017Censu',
 'Totalhouseholds$50000to$74999inincome_2017Census',
 'PercentTotalhouseholds$50000to$74999inincome_2017Censu',
 'Totalhouseholds$75000to$99999inincome_2017Census',
 'PercentTotalhouseholds$75000to$99999inincome_2017Censu',
 'Totalhouseholds$100000to$149999inincome_2017Census',
 'PercentTotalhouseholds$100000to$149999inincome_2017Cen',
 'Totalhouseholds$150000to$199999inincome_2017Census',
 'PercentTotalhouseholds$150000to$199999inincome_2017Cen',
 'Totalhouseholds$200000ormoreinincome_2017Census',
 'PercentTotalhouseholds$200000ormoreinincome_2017Census',
 'TotalhouseholdsMedianhouseholdincomeindollars_2017Census',
 'TotalhouseholdsMeanhouseholdincomeindollars_2017Census',
 'TotalWithcashpublicassistanceincome_2017Census',
 'PercentWithcashpublicassistanceincome_2017Census',
 'Meancashpublicassistanceincomeindollars_2017Census',
 'TotalWithFoodStamp_SNAPbenefitsinthepast12months_2017C',
 'PercentWithFoodStamp_SNAPbenefitsinthepast12months_2017',
 'Families_Medianfamilyincomeindollars_2017Census',
 'Families_Meanfamilyincomeindollars_2017Census',
 'Percapitaincomeindollars_2017Census',
 'Medianearningsforworkersindollars_2017Census',
 'TotalCiviliannoninstitutionalizedpopulation_Nohealthinsura',
 'PercentCiviliannoninstitutionalizedpopulation_Nohealthinsur',
 'TotalCiviliannoninstitutionalizedpopulation19to64yearsIn',
 'PercentCiviliannoninstitutionalizedpopulation19to64years_A',
 'TotalCiviliannoninstitutionalizedpopulation19to64yearsNo',
 'PercentCiviliannoninstitutionalizedpopulation19to64years',
 'PERCENTAGEOFFAMILIESANDPEOPLEWHOSEINCOMEINTHEPAST12MO_D',
 'PERCENTAGEOFFAMILIESANDPEOPLEWHOSEINCOMEINTHEPAST12MO_C',
 'PERCENTAGEOFFAMILIESANDPEOPLEWHOSEINCOMEINTHEPAST12MO_B',
 'PERCENTAGEOFFAMILIESANDPEOPLEWHOSEINCOMEINTHEPAST12MO_A',
 'PERCENTAGEOFFAMILIESANDPEOPLEWHOSEINCOMEINTHEPAST12MO',
 'Population_VSP2017Report',
 'Incidentrateper1000population_VSP2017Report',
 'TotalIncidentsReportedinLocality_VSP2017Report',
 'MurderNonnegligentManslaughter_TotalReportedOffenses_VSP201',
 'KidnappingAbduction_TotalReportedOffenses_VSP2017Report',
 'RapeTotalReportedOffenses_VSP2017Report',
 'OtherForcibleSexOffenses_TotalReportedOffenses_VSP2017Rep',
 'RobberyTotalReportedOffenses_VSP2017Report',
 'Agg.Assault_TotalReportedOffenses_VSP2017Report',
 'SimpleAssaultIntimidation_TotalReportedOffenses_VSP2017Rep',
 'ArsonTotalReportedOffenses_VSP2017Report',
 'ExtortionBlackmailTotalReportedOffenses_VSP2017Report',
 'BurglaryTotalReportedOffenses_VSP2017Report',
 'Larceny_TotalReportedOffenses_VSP2017Report',
 'MotorVehicleTheftTotalReportedOffenses_VSP2017Report',
 'Counterfeiting_ForgeryTotalReportedOffenses_VSP2017Report',
 'Fraud_TotalReportedOffenses_VSP2017Report',
 'EmbezzlementTotalReportedOffenses_VSP2017Report',
 'StolenPropertyTotalReportedOffenses_VSP2017Report',
 'Destruction_VandalismTotalReportedOffenses_VSP2017Report',
 'Drug_NarcoticsTotalReportedOffenses_VSP2017Report',
 'NonForcibleSexOffensesTotalReportedOffenses_VSP2017Report',
 'PornographyTotalReportedOffenses_VSP2017Report',
 'GamblingTotalReportedOffenses_VSP2017Report',
 'ProstitutionTotalReportedOffenses_VSP2017Report',
 'BriberyTotalReportedOffenses_VSP2017Report',
 'WeaponsLawViolationTotalReportedOffenses_VSP2017Report',
 'TotalCrimesAgainstthePerson_ReportedOffenses_VSP2017Repor',
 'TotalCrimesAgainstProperty_OffensesReported_VSP2017Report',
 'TotalCrimesAgainstSociety_OffensesReported_VSP2017Report',
 'ViolentCrime_OffensesReported_VSPDefinition_VSP2017Report',
 'PropertyCime_OffensesReported_VSPDefinition_VSP2017Report',
 'MurderNonnegligentManslaughterADULTArrests_VSP2017Report',
 'Kidnapping_AbductionArrestsADULTArrests_VSP2017Report',
 'RapeADULTArrests_VSP2017Report',
 'OtherForcibleSexoffensesADULTArrests_VSP2017Report',

In [13]:
release = df['WhetherDefendantWasReleasedPretrial']
print(release.unique(), '\n')
print(release.value_counts(), '\n')
release = release.replace(9,np.nan) #9's were a number that should be replaced to np.nan
print(release.value_counts(),'\n')
sum(release.isnull()) # This shows the number of values that are still missing
df['WhetherDefendantWasReleasedPretrial'] = release # This shows your results with missing values cleared
del release

[9 0 1]

WhetherDefendantWasReleasedPretrial
1    19154
0     3801
9       31
Name: count, dtype: int64

WhetherDefendantWasReleasedPretrial
1.0    19154
0.0     3801
Name: count, dtype: int64

In [22]:
length = df['ImposedSentenceAllChargeInContactEvent']
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']
print(length.unique(), '\n') # This shows values that are missing
print(type.unique()) # This shows the values in the Type
length = pd.to_numeric(length,errors='coerce') # This changes to a numeric variable
length_NA = length.isnull() # This will create a dummy variable to represent missing values
print(np.sum(length_NA), '\n') #This shows the number of missing values at 274
print(pd.crosstab(length_NA,type), '\n') #Although the number of missing values was already reduced to 274, these next steps will show how to have reduced to this from a higher number of missing values
# This will examine cases that should be dismissed
length = length.mask(type == 4, 0) # This looks at the cases where charges were dismissed and replaces the length with 0
length = length.mask(type == 9, np.nan) # This will make the length np.nan when the charges are unclear
length_NA = length.isnull() # This creates another dummy variable to represent missing values
print(pd.crosstab(length_NA, type), '\n')
print(np.sum(length_NA),'\n') # This will show a new number of missing values (which should be 274)
df['ImposedSentenceAllChargeInContactEvent'] = length
del length, type

[           nan 6.00000000e+01 1.20000000e+01 9.85626283e-01
 0.00000000e+00 3.60000000e+01 6.00000000e+00 2.40000000e+01
 5.91375770e+00 1.20000000e+02 7.20000000e+01 1.19917864e+01
 2.95687885e+00 8.40000000e+01 1.08000000e+02 3.00000000e+02
 2.40000000e+02 1.80000000e+02 4.00000000e+00 9.60000000e+01
 2.00000000e+00 5.40000000e+01 3.28542094e-01 4.40000000e+01
 5.00000000e+00 1.15000000e+02 1.32000000e+02 4.80000000e+01
 2.58000000e+02 3.40000000e+01 7.60000000e+01 1.64271047e-01
 1.31416838e-01 1.11000000e+02 9.00000000e+00 3.00000000e+00
 1.97125257e+00 3.69856263e+01 6.57084189e-02 3.54928131e+01
 1.06492813e+02 8.00000000e+00 3.50000000e+01 1.83141684e+01
 4.80000000e+02 3.20000000e+01 9.30000000e+01 2.34000000e+02
 7.32000000e+02 1.16427105e+00 4.65708419e+00 2.10000000e+01
 7.00000000e+00 4.49281314e+00 1.80000000e+01 6.00000000e+02
 4.31642710e+01 1.79000000e+02 5.20000000e+01 3.00000000e+01
 2.00000000e+01 1.92000000e+02 7.02000000e+02 1.40000000e+01
 5.50000000e+01 5.30000000e+01 1.19055441e+01 1.14000000e+02
 3.50061602e+01 6.80000000e+01 6.57084189e-01 4.66242300e+01
 1.02000000e+02 6.50000000e+01 2.00000000e+02 5.70000000e+01
 2.43285421e+01 1.21642710e+01 1.17000000e+02 8.14928131e+01
 2.24928131e+01 1.98000000e+03 3.65708419e+00 5.60000000e+01
 1.00000000e+01 2.79260780e+00 1.00000000e+00 4.70000000e+01
 2.20000000e+01 1.50000000e+03 4.00000000e+01 2.84000000e+02
 1.10000000e+01 1.18000000e+02 4.20000000e+01 1.62000000e+02
 1.56000000e+02 4.72956879e+01 1.05000000e+02 5.10000000e+01
 2.46000000e+02 2.90000000e+01 7.50000000e+01 3.24000000e+02
 3.60000000e+02 3.44804928e+01 1.20328542e+02 5.99260780e+01
 6.60000000e+01 5.99917864e+01 6.60000000e+02 5.11642710e+01
 1.49568789e+01 3.98562628e+00 7.80000000e+01 2.28000000e+02
 1.47843943e+00 6.20000000e+01 4.80000000e+00 8.60000000e+01
 1.68000000e+02 2.30000000e+01 3.30000000e+01 4.80328542e+01
 7.20000000e+02 3.48000000e+02 1.20000000e+03 2.70000000e+01
 4.90000000e+01 8.70000000e+01 4.20000000e+02 6.30000000e+01
 7.99260780e+01 5.70349076e+01 4.99712526e+01 5.94928131e+01
 1.70000000e+01 2.38492813e+02 6.09856263e+01 1.26000000e+02
 4.50000000e+01 1.58000000e+02 2.16000000e+02 2.27000000e+02
 4.29568789e+01 4.45000000e+02 7.09527721e+01 5.16000000e+02
 1.77821355e+02 1.75200000e+03 9.00000000e+01 1.08000000e+03
 1.41000000e+02 4.82956879e+00 2.30000000e+02 3.10000000e+01
 2.20800000e+03 5.25133470e+01 6.90000000e+01 2.60000000e+01
 3.34928131e+01 1.40000000e+02 1.31000000e+02 3.44000000e+02
 2.19000000e+02 1.01000000e+02 7.10000000e+01 5.90000000e+01
 5.80000000e+01 1.20197125e+02 6.70000000e+01 3.54004107e+01
 3.28542094e+00 4.01642710e+01 9.10000000e+01 1.77412731e+00
 1.55000000e+02 3.44928131e+01 8.10000000e+01 9.23285421e+01
 3.54825462e+00 2.07000000e+02 7.40000000e+01 5.18000000e+02
 2.80000000e+01 8.95687885e+00 2.37000000e+02 4.04673511e+02
 1.81642710e+01 1.07433265e+01 5.51000000e+02 3.90000000e+01
 1.50000000e+01 1.24000000e+02 4.30000000e+01 1.76000000e+02
 1.94928131e+01 4.82000000e+02 1.29000000e+02 8.80000000e+01
 4.60000000e+01 4.58542094e+01 1.28628337e+02 1.36492813e+02
 1.08328542e+02 5.00000000e+01 3.63663244e+02 2.88000000e+02
 2.50000000e+02 1.07000000e+02 8.10225873e+01 4.44000000e+02
 2.05000000e+02 1.06570842e+01 1.90000000e+01 6.69856263e+01
 3.84928131e+01 2.64000000e+02 2.76000000e+02 1.73000000e+02
 2.22000000e+02 1.44000000e+02 2.94000000e+02 3.36000000e+02
 4.31000000e+02 4.50000000e+02 7.30000000e+01 9.93285421e+01
 1.28000000e+02 3.08069815e+01 3.15256674e+01 1.27000000e+02
 2.02000000e+02 5.53285421e+01 8.90000000e+01 2.42000000e+02
 1.31416838e+00 1.02900000e+03 7.88501027e-01 1.94858316e+02
 3.99000000e+02 3.96570842e+01 5.69568789e+01 1.98000000e+02
 1.20985626e+02 4.76570842e+01 1.48000000e+02 6.89938398e+00
 6.53285421e+01 5.95277207e+00 9.85626283e-02 3.32854209e+00
 3.94250513e+00 1.29856263e+01 6.98562628e+00 1.31498973e+01
 1.51642710e+01 1.71971253e+01 1.79137577e+01 1.04000000e+02
 2.12000000e+02 2.46570842e+01 7.26570842e+01 2.98562628e+00
 1.44985626e+02 3.19712526e+01 1.83000000e+02 4.98562628e+00
 1.18213552e+01 2.52000000e+02 1.23942505e+01 4.24928131e+01
 1.01642710e+01 1.11642710e+01 5.49281314e+00 5.96632444e+01
 1.23285421e+01 4.89856263e+01 2.40985626e+02 2.65708419e+00
 5.40000000e+02 2.97125257e+00 6.32854209e+00 2.36632444e+01
 1.33657084e+02 3.53285421e+01 4.56000000e+02 1.03000000e+02
 1.72279261e+00 1.26570842e+01 1.16570842e+01 6.03285421e+01
 3.78850103e+00 5.76000000e+02 2.13141684e+00 4.92000000e+02
 1.49856263e+01 2.49856263e+01 6.19712526e+01 5.65708419e+00
 1.60000000e+01 4.21642710e+01 4.92813142e-01 1.38000000e+02
 1.33141684e+01 1.18932238e+01 5.32854209e+00 9.50000000e+01
 6.26570842e+01 3.08829569e+00 1.18275154e+01 1.64271047e+00
 4.79917864e+01 4.27104723e+00 8.32854209e+00 3.31416838e+00
 7.00000000e+01 7.70000000e+01 1.09856263e+00 4.81642710e+01
 2.74928131e+01 6.93839836e+00 1.01100000e+03 6.89938398e-01
 1.11704312e+00 1.49281314e+00 4.16427105e+00 1.19712526e+00
 4.07392197e+00 1.88000000e+02 1.13285421e+01 3.28542094e-02
 4.32000000e+02 1.19527721e+01 3.64928131e+01 2.39835729e+01
 9.98562628e+00 9.80000000e+01 3.63285421e+01 1.12000000e+02
 3.94250513e-01 1.30000000e+01 2.62833676e-01 1.37987680e+01
 5.88706366e+00 3.54000000e+02 5.91991786e+00 2.41642710e+01
 6.29568789e+01 4.59958932e+00 1.23000000e+02 2.32854209e+00
 2.39240246e+01 2.04000000e+02 1.97000000e+02 1.74000000e+02
 1.61498973e+01 8.40000000e+02 4.40000000e+02 9.89568788e+01
 1.79527721e+01 6.39425051e+01 6.01314168e+01 1.21314168e+01
 1.72952772e+02 1.97125257e-01 1.38164271e+02 4.92813142e+00
 9.19917864e-01 1.89856263e+01 6.65708419e+00 2.85420945e+00
 8.91375770e+00 1.46000000e+02 1.24928131e+01 5.58521561e-01
 7.22792608e-01 5.82135524e+00 8.49856263e+01 6.16427105e+00
 1.59856263e+01 6.45585216e+01 3.82997947e+01 1.19589322e+01
 3.12114990e+00 1.26328542e+02 5.16427105e+00 6.40000000e+01
 4.26570842e+01 3.12000000e+02 1.99712526e+01 8.23285421e+01
 2.39712526e+01 1.76242300e+01 1.21971253e+02 5.96550308e+01
 1.32854209e+00 7.97125257e+00 1.91991786e+00 5.25667351e-01
 9.32854209e+00 4.29856263e+01 4.19137577e+01 7.29856263e+01
 1.24784394e+01 5.19096509e+00 4.73000000e+02 1.66570842e+01
 1.09000000e+02 8.63285421e+01 4.10000000e+01 1.90554415e+00
 9.41642710e+01 3.02000000e+02 4.39425051e+00 1.08213552e+01
 1.83285421e+01 1.54000000e+02 8.30000000e+01 1.10956879e+02
 2.26000000e+02 9.60328542e+01 4.82135524e+00 3.03285421e+01
 3.79712526e+01 5.04640657e+01 2.86000000e+02 9.90000000e+01
 9.94928131e+01 2.66119097e+00 7.09712526e+01 1.39712526e+01
 2.36570842e+01 4.59958932e-01 1.32492813e+02 2.83000000e+02
 4.93141684e+01 2.79856263e+01 3.80000000e+01 7.65708419e+00
 8.36550308e+01 1.09199179e+01 1.62328542e+02 3.70000000e+01
 1.32328542e+02 3.59527721e+01 1.65000000e+02 1.09856263e+01
 2.01642710e+01 2.59137577e+00 1.75000000e+02 1.80985626e+02
 1.03285421e+01 3.61642710e+01 1.20657084e+02 2.32000000e+02
 1.52000000e+02 8.98562628e+00 1.67000000e+02 1.10657084e+01
 1.12032854e+01 5.19712526e+00 3.16427105e+00 6.01642710e+01
 1.18275154e+00 2.11642710e+01 2.19712526e+00 4.19712526e+00
 2.62833676e+00 1.19952772e+02 1.19958932e+02 9.49281314e+00
 5.25667351e+00 1.53285421e+01 2.82135524e+00 1.92985626e+02
 4.86570842e+01 5.95687885e+00 2.29979466e+00 9.60000000e+02
 2.36550308e+00 1.16000000e+02 1.95133470e+01 1.65708419e+00]

[9 0 1 4 2]
274

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

274